spring.application.name=apartmentmanager

# Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/apartmentmanager
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


#JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Dialect acts as a translator - converts Hibernate queries to PostgreSQL specific SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Config
jwt.secret=yourSecretKey404E635266556A586E3272357538782F413F4428472B4B6250645367566B59
jwt.expiration=86400000

# Mail Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=youremail@gmail.com
spring.mail.password=yourgmailapppassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

